### ISSUE TITLE
astropy 3.0 requirement breaks python2.7 installl

### ISSUE THREAD

**Issue by ygrange** [darafferty/LSMTool#12]
Whgen  try to install LSMtool using setup.py, it will install astropy as a requirement. The astropy install for 3.0 rc1 fails to install in python2.7. As a quick fix I tweaked my local version the the setup.py to `install_requires=['numpy','astropy >= 0.4, <3.0'],`.  That works for now. Not sure what the planning for the future is though.

**Comment by darafferty** [comment]
Thanks! I have added a check to setup.py that uses your fix to adjust the required astropy version depending on the python version.
