### ISSUE TITLE
wcsaxes is deprecated 

### ISSUE THREAD

**Issue by gijzelaerr** [darafferty/LSMTool#13]
wcsaxes is deprecated since a while and going to be replaced by astropy. It is not part of Debian and ubuntu anymore.

**Comment by gijzelaerr** [comment]
hi! Thanks for your reply. The code you are pointed to is unfortunately unreleased.

**Comment by darafferty** [comment]
Ah -- I see. I will make a new release.

**Comment by darafferty** [comment]
Issue should be addressed now in the v1.3.1 release.
